module.exports.EVENTS = {
    CONNECTING: 'NEW-USER',
    DISCONNECTING: 'USER-DISCONNECTED',
    SEND_MESSAGE: 'SEND-MESSAGE',
    CONNECTED_USERS: 'CONNECTED_USERS',
}

module.exports.IMAGE_AMOUNT = 8;
